name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker build -t utkarshhitachi/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run --rm -e CI=true utkarshhitachi/react-test npm test -- --watchAll=false
 
      - run: docker build -t utkarshhitachi/multi-client ./client
      - run: docker build -t utkarshhitachi/multi-nginx ./nginx
      - run: docker build -t utkarshhitachi/multi-server ./server
      - run: docker build -t utkarshhitachi/multi-worker ./worker
 
      - run: docker push utkarshhitachi/multi-client
      - run: docker push utkarshhitachi/multi-nginx
      - run: docker push utkarshhitachi/multi-server 
      - run: docker push utkarshhitachi/multi-worker
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multid
          environment_name: Multid-env 
          existing_bucket_name: elasticbeanstalk-ap-south-1-438601906527
          region: ap-south-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip